name: olam
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.2.3
  iconly: ^1.0.1
  mobile_scanner: ^7.2.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  logger: ^2.6.2
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  get_storage: ^2.1.1
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter Launcher Icons konfiguratsiyasi
flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash/img.png"

flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/bottom_nav_bar/
    - assets/home/